adj1 = input("Enter an adjective(description of a place): ")
adj2 = input("Enter an adjective(description of an animal): ")
adj3 = input("Enter an adjective(description of an animal): ")
adj4 = input("Enter an adjective(description of a situation): ")
noun1 = input("Enter a noun(place): ")
noun2 = input("Enter a noun(animal): ")
verb1 = input("Enter a verb(do something with animal): ")
print(f"Yesterday, we went to a {adj1} {noun1}")
print(f"In that {noun1}, I saw a {adj2} {noun2}")
print(f"The {noun2} was playing with its buddy. Its buddy looks {adj3}")
print(f"The {adj3} {noun2} come running to us. ")
print(f"It was a {adj4} situation")
print(f"I want to {verb1}")
